# Memory for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Run subprojects in parallel
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true

# Kotlin default
kotlin.code.style=official

# Only build resources for the current variant
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
